<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExperienceSeeder extends Seeder
{
    public function run()
    {
        DB::table('experiences')->insert([
            [
                'client' => 'PT Freeport Indonesia',
                'project_name' => 'Large Bore & SAG Building Pipe Fabrication',
                'location' => 'Gunanusa Yard, Grenyang',
                'scope_of_work' => 'Supply and Fabrication',
                'description' => 'Large Bore & SAG Building Pipe Fabrication for Mill Optimization for UG Ores - Phase 1',
                'project_duration' => '04 April 22 - May 2023',
                'image' => null,
            ],
            [
                'client' => 'PTTEP International Limited',
                'project_name' => 'EPCI of Wellhead Platforms, Associated Pipelines and Brownfield Modification for Zawtika Development Project Phase 1D',
                'location' => 'Gulf of Moattama, 300 km South of Yangon, Myanmar',
                'scope_of_work' => 'EPCI',
                'description' => "Work Packages 1: 4 Wellhead Platforms (ZWP12, ZWP13, ZWP14 & ZWP15)\nWork Packages 2: Pipelines\nWork Packages 3: Brownfield Modification",
                'project_duration' => '01 Mar 21 - 28 Feb 23',
                'image' => null,
            ],
            [
                'client' => 'PT Saipem Indonesia',
                'project_name' => 'Fabrication of Piles, Sea fastening & Grillage for Jackets',
                'location' => 'Gunanusa Yard, Grenyang',
                'scope_of_work' => 'Fabrication',
                'description' => 'Fabrication of Piles, Sea fastening & Grillage for Jackets of Qatar Gas NFPS Project',
                'project_duration' => '25 Mar 22 - 31 Mar 23',
                'image' => null,
            ],
            [
                'client' => 'PT. Synthetic Rubber Indonesia',
                'project_name' => '3rd Batch - Stripping Spool Replacement - Duplex Spool Replacement',
                'location' => 'Cilegon, Indonesia',
                'scope_of_work' => 'Fabrication',
                'description' => 'Supply, Fabrication , Demolition & Installation Duplex Piping',
                'project_duration' => 'April 21 - Dec 21',
                'image' => null,
            ],
            [
                'client' => 'PGN SAKA',
                'project_name' => 'Provision of EPCIC Services for Sidayu Wellhead Platforms and Pipelines',
                'location' => 'Gresik, Jawa Timur',
                'scope_of_work' => 'EPCIC',
                'description' => "Provision of EPCIC Services for Sidayu Wellhead Platforms and Pipelines\n2 x Offshore Wellhead Platforms (WHP-C and WHP-D)\nWHP-C; 336 MT Jacket & 471 MT Topside\nWHP-D; 217 MT Jacket & 485 MT Topside\nTwo (2) Associated Pipelines 6\" & 12\" FOR 2.5 km\nModification",
                'project_duration' => 'Dec 19 - Dec 21',
                'image' => null,
            ],
            [
                'client' => 'MITSUI Engineering & Shipbuilding Co., Ltd.',
                'project_name' => 'Fabrication of Cooling Water Pipe',
                'location' => 'Central Java, Indonesia',
                'scope_of_work' => 'Fabrication',
                'description' => 'Pipe Fabrication, Pipe Erection & Installation of Cooling Water Pipe 4.2m x 3km in segments 39 m, 36 m, 10 m, 5 m with total weight 8,200 Ton.',
                'project_duration' => 'Dec 19 - Dec 21',
                'image' => null,
            ],
            [
                'client' => 'Konsorsium PT Seirama Laju & PT. Hafar Daya Konstruksi',
                'project_name' => 'Supply of Anchor Mooring Piles and PLEM Piiles',
                'location' => 'Gunanusa Yard, Cilegon',
                'scope_of_work' => 'Fabrication',
                'description' => 'Supply Material and Fabrication of Belawan SPM Piles and PLEM Piles',
                'project_duration' => 'Jan 21 - Apr 21',
                'image' => null,
            ],
            [
                'client' => 'PT WASKITA KARYA(Persero) Tbk Infrastructure 2 Division',
                'project_name' => 'Fabrication of Jembatan Lintas Ahmad Yani (SB-Arch)',
                'location' => 'Becakayu Seksi 2A - Ujung, Jakarta, Indonesia',
                'scope_of_work' => 'Fabrication',
                'description' => 'Tekla Modelling, Procurement, Fabrication and Erection of Bridge for Ahmad Yani (Span 53+100+60 m) and Hasibuan (80 m) of SBArch Girders',
                'project_duration' => 'Jun 19 - Mar 21',
                'image' => null,
            ],
            [
                'client' => 'PT WASKITA KARYA(Persero) Tbk Infrastructure 2 Division',
                'project_name' => 'Fabrication of Bridge Akses Arteri Hasibuan',
                'location' => 'Becakayu Seksi 2A - Ujung, Jakarta, Indonesia',
                'scope_of_work' => 'Fabrication',
                'description' => 'Tekla Modelling, Procurement, Fabrication and Erection of Bridge for Ahmad Yani (Span 53+100+60 m) and Hasibuan (80 m) of SBArch Girders',
                'project_duration' => 'Jun 19 - Mar 21',
                'image' => null,
            ],
            [
                'client' => 'MITSUI Engineering & Shipbuilding Co., Ltd.',
                'project_name' => 'Fabrication of Additional Steel Pipe of Cooling Water Lines - Lot 3 and Modification of Steel Pipe',
                'location' => 'Central Java, Indonesia',
                'scope_of_work' => 'Fabrication and Modification',
                'description' => 'Fabrication of Additional Steel Pipe of Cooling Water Lines\nLot 3 and Modification of Steel Pipe',
                'project_duration' => 'Aug 20 - Dec 20',
                'image' => null,
            ],
            [
                'client' => 'Pertamina Hulu Energi ONWJ',
                'project_name' => 'Provision of Removal Platform YYA',
                'location' => 'Offshore North West Java',
                'scope_of_work' => 'Procurement, Fabrication, Unloading and Inland Transportation of YYA Platform Component',
                'description' => 'Procurement, Fabrication, Unloading and Inland Transportation of YYA Platform',
                'project_duration' => '2020',
                'image' => null,
            ],
            [
                'client' => 'WASKITA ACSET - KSO',
                'project_name' => 'Fabrication of Steel Box Girder Toll Road Jakarta - Cikampek II(Elevated)',
                'location' => 'Grand Wisata, West Java, Indonesia',
                'scope_of_work' => 'Fabrication & Installation',
                'description' => 'Fabrication of Steel Box Girder Toll Road Jakarta - Cikampek II (Elevated)',
                'project_duration' => '2018-2019',
                'image' => null,
            ],
            [
                'client' => 'BUKAKA',
                'project_name' => 'Fabrication of Steel I Girder Japek Sungai Cikarang',
                'location' => 'Cikarang, West Java, Indonesia',
                'scope_of_work' => 'Fabrication',
                'description' => 'Fabrication of Steel I Girder Japek Sungai Cikarang',
                'project_duration' => '2019',
                'image' => null,
            ],
            [
                'client' => 'PT. Wijaya Karya Industri & Konstruksi',
                'project_name' => 'PT. Wijaya Karya Industri & Konstruksi Main Road Box',
                'location' => 'Toll Road Serpong - Kunciran and North Kalimantan',
                'scope_of_work' => 'Fabrication',
                'description' => 'Fabrication of Bridge and Box Girder',
                'project_duration' => '2018-2019',
                'image' => null,
            ],
            [
                'client' => 'BLUEWATER',
                'project_name' => 'Manufacturing of 3 Units CALM BUOYS for PT. Pertamina (Persero), Indonesia',
                'location' => 'Semarang, Jakarta and Belawan',
                'scope_of_work' => 'Procurement, Fabrication, Storage',
                'description' => 'Fabrication and Assembly, Pre-Commissioning and Testing, Load Out to Offshore, Offshore Commissioning',
                'project_duration' => '2017-2018',
                'image' => null,
            ],
            [
                'client' => 'ONGC - INDIA',
                'project_name' => 'Daman Development Project (Piles & Conductor) - India',
                'location' => 'Daman Sea - India',
                'scope_of_work' => 'Fabrication',
                'description' => 'Fabrication and Supply of Piles and Conductors of Well Platforms for Daman Development Project',
                'project_duration' => '2017-2018',
                'image' => null,
            ],
            [
                'client' => 'PTTEP International Limited',
                'project_name' => 'EPCI OF WHP, Associated Pipeline & Tie-In For Zawtika Field Development Project Phase 1c (WHP & Pipelins & Tie In)',
                'location' => 'Gulf of Moattama, 300 km South of Yangon, Myanmar',
                'scope_of_work' => 'Engineering, Procurement, Construction, Installation, Hook-up and Commissioning',
                'description' => "Lot 1: WP8 & WP9; Lot 2: WP 10 & WP11\n- 4 x Wellhead Platforms: 6,450 MT\n- 4 x Jacket average : 6,560 MT\n- 4 sets piles @ 6500 tons, total 26,000 tons\n- Four (4) Associated Pipelines in total 67 KM, 18\" and 16\"\n- Two (2) Pipeline and Manifold (PLEM)\n- Brownfield Modification and Tie-in to Existing Platform\n- Water Depth = 142-156 meter CD",
                'project_duration' => '2016-2018',
                'image' => null,
            ],
            [
                'client' => 'PT Pertamina Hulu Energi -West Madura Offshore (PHE-WMO)',
                'project_name' => 'EPCI-1 SERVICE CONTRACT for: PHE- 12, PHE-24 and CPP2 Platforms and Pipeline.',
                'location' => 'West Madura Offshore - Indonesia',
                'scope_of_work' => 'Engineering, Procurement, Construction, Installation, Hook-up & Commissioning',
                'description' => "- PHE-12 Deck : 465 MT, Jacket : 463 MT, Piles : 264 MT, Braced Monopod, 3 legs (2 battered sleeve & 1 caisson sleeve)\n- PHE-24 Deck : 330 MT, Jacket : 453 MT, Piles : 264 MT, Braced Monopod, 3 legs (2 battered sleeve & 1 caisson sleeve)\n- CPP2 Deck : 2500 MT, Jacket : 1200 MT, Piles : 1240 MT & Bridges : 50 MT, 4-legs with double better 1:10",
                'project_duration' => '2015-2017',
                'image' => null,
            ],
            [
                'client' => 'Swiber / ONGC',
                'project_name' => 'ONGC - DAMAN DEVELOPMENT PROJECT',
                'location' => 'Adaman Sea Around 60 Km offshore-India',
                'scope_of_work' => 'Fabrication 3 Jackets & 3 Topsides',
                'description' => 'Fabrication of\n- Topsides and Jackets of C24-P3 Platform ,\n- Topsides and Jackets of C24-P4 Platform,\n- Topsides and Jackets of C24-RP Platform,\n- Bridge from C24-RP to C24-P1',
                'project_duration' => '2015-2016',
                'image' => null,
            ],
            [
                'client' => 'Petronas Carigali Ketapang II Ltd',
                'project_name' => 'BTJT-A TOPSIDE MODIFICATION, ADAPTOR FABRICATION AND PILE MAKE-UP FOR BUKIT TUA DEVELOPMENT PROJECT',
                'location' => '35 km north of Madura Island and 110 km northeast of Gresik',
                'scope_of_work' => 'Topside Modification, Fabrication Pile Make Up, Fabrication Adapter',
                'description' => '- Topside Modification\n- Fabrication Pile Make Up\n- Fabrication Adapter',
                'project_duration' => '2014',
                'image' => null,
            ],

        ]);
    }
}
